/* Generated By:JJTree&JavaCC: Do not edit this line. CYKPARSERConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CYKPARSERConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LF = 4;
  /** RegularExpression Id. */
  int LFLF = 5;
  /** RegularExpression Id. */
  int VARIABLE = 6;
  /** RegularExpression Id. */
  int TS = 7;
  /** RegularExpression Id. */
  int TERMINAL = 8;
  /** RegularExpression Id. */
  int DIVISION = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\" \\n\"",
    "<VARIABLE>",
    "<TS>",
    "<TERMINAL>",
    "\"->\"",
  };

}
