/* Generated By:JavaCC: Do not edit this line. CYKPARSERTreeConstants.java Version 5.0 */
package parser;

public interface CYKPARSERTreeConstants
{
  public int JJTSTART = 0;
  public int JJTASSIGNMNT = 1;


  public String[] jjtNodeName = {
    "START",
    "ASSIGNMNT",
  };
}
/* JavaCC - OriginalChecksum=84151985ebcbb12fb64f10e95b6d827e (do not edit this line) */
